Bump github.com/grafana/grafana-plugin-sdk-go from 0.260.3 to 0.261.0 in /plugin in the all group (#572)
Bumps the all group in /plugin with 1 update:
[github.com/grafana/grafana-plugin-sdk-go](https://github.com/grafana/grafana-plugin-sdk-go).

Updates `github.com/grafana/grafana-plugin-sdk-go` from 0.260.3 to
0.261.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/grafana/grafana-plugin-sdk-go/releases">github.com/grafana/grafana-plugin-sdk-go's
releases</a>.</em></p>
<blockquote>
<h2>v0.261.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Mark TLS certificate verification error as downstream by <a
href="https://github.com/ivanahuckova"><code>@​ivanahuckova</code></a>
in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1171">grafana/grafana-plugin-sdk-go#1171</a></li>
<li>build(deps): bump go.opentelemetry.io/otel/exporters/otlp/otlptrace
from 1.32.0 to 1.33.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1172">grafana/grafana-plugin-sdk-go#1172</a></li>
<li>build(deps): bump
go.opentelemetry.io/otel/exporters/otlp/otlptrace/otlptracegrpc from
1.32.0 to 1.33.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1173">grafana/grafana-plugin-sdk-go#1173</a></li>
<li>build(deps): bump go.opentelemetry.io/contrib/propagators/jaeger
from 1.32.0 to 1.33.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1175">grafana/grafana-plugin-sdk-go#1175</a></li>
<li>build(deps): bump github.com/grpc-ecosystem/go-grpc-middleware/v2
from 2.1.0 to 2.2.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1174">grafana/grafana-plugin-sdk-go#1174</a></li>
<li>Chore: update dependencies by <a
href="https://github.com/ryantxu"><code>@​ryantxu</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1186">grafana/grafana-plugin-sdk-go#1186</a></li>
<li>build(deps): bump go.opentelemetry.io/contrib/samplers/jaegerremote
from 0.26.0 to 0.27.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1182">grafana/grafana-plugin-sdk-go#1182</a></li>
<li>build(deps): bump
go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc
from 0.57.0 to 0.58.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1183">grafana/grafana-plugin-sdk-go#1183</a></li>
<li>build(deps): bump google.golang.org/grpc from 1.68.1 to 1.69.2 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1180">grafana/grafana-plugin-sdk-go#1180</a></li>
<li>Fix missing info severity level in JSON for notices in frame meta by
<a href="https://github.com/zenador"><code>@​zenador</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1185">grafana/grafana-plugin-sdk-go#1185</a></li>
<li>Enrich errors with error source using grpc status package by <a
href="https://github.com/wbrowne"><code>@​wbrowne</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1163">grafana/grafana-plugin-sdk-go#1163</a></li>
<li>Do not log error when standlone.txt does not exist by <a
href="https://github.com/wbrowne"><code>@​wbrowne</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1188">grafana/grafana-plugin-sdk-go#1188</a></li>
<li>Fix: Check for missing client config in secure socks proxy check by
<a href="https://github.com/kevinwcyu"><code>@​kevinwcyu</code></a> in
<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1179">grafana/grafana-plugin-sdk-go#1179</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/zenador"><code>@​zenador</code></a> made
their first contribution in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1185">grafana/grafana-plugin-sdk-go#1185</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.260.3...v0.261.0">https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.260.3...v0.261.0</a></p>
<h2>Compatibility</h2>
<pre><code>gorelease -base=v0.260.3 -version=v0.261.0           
<h1>github.com/grafana/grafana-plugin-sdk-go/backend</h1>
<h2>compatible changes</h2>
<p>ErrorSourceFromGrpcStatusError: added<br />
IsPluginError: added</p>
<h1>github.com/grafana/grafana-plugin-sdk-go/experimental/status</h1>
<h2>compatible changes</h2>
<p>IsPluginError: added</p>
<h1>summary</h1>
<p>v0.261.0 is a valid semantic version for this release.<br />
</code></pre></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/5364a9d4e74bc098c8079cbfd052155aa0a70e64"><code>5364a9d</code></a>
Fix: Check for missing client config in secure socks proxy check (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1179">#1179</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/75f67e70fa041924012939d6d5bf2a91895650c4"><code>75f67e7</code></a>
do not log error when standlone.txt does not exist (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1188">#1188</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/bd0a1c577a661178a1ac4819db70aa30f75744ab"><code>bd0a1c5</code></a>
Enrich errors with error source using grpc status package (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1163">#1163</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/bba8d977c63c6c5615c6a04635c314a4d3881849"><code>bba8d97</code></a>
Fix missing info severity level in JSON for notices in frame meta (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1185">#1185</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/ab5e6501ceb0a1fe35759fcb7e10ec2491d2ece6"><code>ab5e650</code></a>
build(deps): bump google.golang.org/grpc from 1.68.1 to 1.69.2 (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1180">#1180</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/c8a816f050e435a5f9a9564132b8c1840c70d75c"><code>c8a816f</code></a>
build(deps): bump
go.opentelemetry.io/contrib/instrumentation/google.golang.o...</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/784c1da1d368e9ba2fe55cb32bf1fd82ab179fce"><code>784c1da</code></a>
build(deps): bump go.opentelemetry.io/contrib/samplers/jaegerremote (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1182">#1182</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/2d235eaecfe44aba8973af2a579b27ef77a0ce36"><code>2d235ea</code></a>
Update deps (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1186">#1186</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/01217aeec5ce34cc87085f0656ea31438d9ed359"><code>01217ae</code></a>
build(deps): bump github.com/grpc-ecosystem/go-grpc-middleware/v2 (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1174">#1174</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/17e066661dd9708b6f31eee467e33b68d0ed42eb"><code>17e0666</code></a>
build(deps): bump go.opentelemetry.io/contrib/propagators/jaeger (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1175">#1175</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.260.3...v0.261.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=github.com/grafana/grafana-plugin-sdk-go&package-manager=go_modules&previous-version=0.260.3&new-version=0.261.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>