Bump the all group in /plugin with 2 updates (#436)
Bumps the all group in /plugin with 2 updates:
[github.com/grafana/grafana-plugin-sdk-go](https://github.com/grafana/grafana-plugin-sdk-go)
and
[github.com/prometheus/client_golang](https://github.com/prometheus/client_golang).

Updates `github.com/grafana/grafana-plugin-sdk-go` from 0.252.0 to
0.253.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/grafana/grafana-plugin-sdk-go/releases">github.com/grafana/grafana-plugin-sdk-go's
releases</a>.</em></p>
<blockquote>
<h2>v0.253.0</h2>
<h2>What's Changed</h2>
<ul>
<li>Error source HTTP client middleware by <a
href="https://github.com/marefr"><code>@​marefr</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1106">grafana/grafana-plugin-sdk-go#1106</a></li>
<li>Error source handler middleware by <a
href="https://github.com/marefr"><code>@​marefr</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1101">grafana/grafana-plugin-sdk-go#1101</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.252.0...v0.253.0">https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.252.0...v0.253.0</a></p>
<h2>Compatibility</h2>
<p>Below incompatible changes should be compatible since we've
introduced type aliases and seems like <code>gorelease</code> doesn't
take that into consideration. Main change is changing
<code>backend.ErrorSource</code> to a type alias for
<code>status.Source</code>.</p>
<pre><code>gorelease -base v0.252.0 -version v0.253.0
# github.com/grafana/grafana-plugin-sdk-go/backend
## incompatible changes
DataResponse.ErrorSource: changed from ErrorSource to
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source
DefaultErrorSource: changed from ErrorSource to
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source
ErrDataResponseWithSource: changed from func(Status, ErrorSource,
string) DataResponse to func(Status,
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source,
string) DataResponse
ErrorSource: changed from ErrorSource to
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source
ErrorSourceDownstream: changed from ErrorSource to
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source
ErrorSourceFromHTTPStatus: changed from func(int) ErrorSource to
func(int)
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source
ErrorSourcePlugin: changed from ErrorSource to
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source
FrameResponseWithErrorAndSource: changed from
func(github.com/grafana/grafana-plugin-sdk-go/data.Framer, error,
ErrorSource) *DataResponse to
func(github.com/grafana/grafana-plugin-sdk-go/data.Framer, error,
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source)
*DataResponse
WithErrorSource: changed from func(context.Context, ErrorSource) error
to func(context.Context,
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source)
error
## compatible changes
ErrorSourceFromContext: added
ErrorSourceMiddleware: added
IsDownstreamHTTPError: added
NewErrorSourceMiddleware: added
<h1>github.com/grafana/grafana-plugin-sdk-go/backend/httpclient</h1>
<h2>compatible changes</h2>
<p>ErrorSourceMiddleware: added<br />
ErrorSourceMiddlewareName: added</p>

<h1>github.com/grafana/grafana-plugin-sdk-go/experimental/errorsource</h1>
<h2>incompatible changes</h2>
<p>Error.ErrorSource: changed from func()
github.com/grafana/grafana-plugin-sdk-go/backend.ErrorSource to func()
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source<br
/>
Error.Source: changed from func()
github.com/grafana/grafana-plugin-sdk-go/backend.ErrorSource to func()
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source<br
/>
FromStatus: changed from
func(github.com/grafana/grafana-plugin-sdk-go/backend.Status)
github.com/grafana/grafana-plugin-sdk-go/backend.ErrorSource to
func(github.com/grafana/grafana-plugin-sdk-go/backend.Status)
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source<br
/>
New: changed from func(error,
github.com/grafana/grafana-plugin-sdk-go/backend.ErrorSource,
github.com/grafana/grafana-plugin-sdk-go/backend.Status) Error to
func(error,
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source,
github.com/grafana/grafana-plugin-sdk-go/backend.Status) Error<br />
SourceError: changed from
func(github.com/grafana/grafana-plugin-sdk-go/backend.ErrorSource,
error, bool) Error to
func(github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source,
error, bool) Error</p>
<h1>github.com/grafana/grafana-plugin-sdk-go/experimental/slo</h1>
<h2>incompatible changes</h2>
<p>FromStatus: changed from
func(github.com/grafana/grafana-plugin-sdk-go/backend.Status)
github.com/grafana/grafana-plugin-sdk-go/backend.ErrorSource to
func(github.com/grafana/grafana-plugin-sdk-go/backend.Status)
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source</p>
<h1>github.com/grafana/grafana-plugin-sdk-go/experimental/status</h1>
<h2>compatible changes</h2>
<p>package added<br />
&lt;/tr&gt;&lt;/table&gt;<br />
</code></pre></p>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/0afdd23fd2176aead359ec566c9ae9151770b6a4"><code>0afdd23</code></a>
Error source handler middleware (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1101">#1101</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/64eea532a8b15269e85a6d507dc8f9f8e9909a4f"><code>64eea53</code></a>
Error source HTTP client middleware (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1106">#1106</a>)</li>
<li>See full diff in <a
href="https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.252.0...v0.253.0">compare
view</a></li>
</ul>
</details>
<br />

Updates `github.com/prometheus/client_golang` from 1.20.4 to 1.20.5
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/prometheus/client_golang/releases">github.com/prometheus/client_golang's
releases</a>.</em></p>
<blockquote>
<h2>v1.20.5 / 2024-10-15</h2>
<p>We decided to revert <a
href="https://redirect.github.com/prometheus/client_golang/pull/1424">the
<code>testutil</code> change</a> that made our util functions less
error-prone, but created a lot of work for our downstream users.
Apologies for the pain! This revert should not cause any major breaking
change, even if you already did the work--unless you depend on the <a
href="https://redirect.github.com/grafana/mimir/pull/9624#issuecomment-2413401565">exact
error message</a>.</p>
<p>Going forward, we plan to reinforce our release testing strategy <a
href="https://redirect.github.com/prometheus/client_golang/issues/1646">[1]</a>,<a
href="https://redirect.github.com/prometheus/client_golang/issues/1648">[2]</a>
and deliver an enhanced <a
href="https://redirect.github.com/prometheus/client_golang/issues/1639"><code>testutil</code>
package/module</a> with more flexible and safer APIs.</p>
<p>Thanks to <a
href="https://github.com/dashpole"><code>@​dashpole</code></a> <a
href="https://github.com/dgrisonnet"><code>@​dgrisonnet</code></a> <a
href="https://github.com/kakkoyun"><code>@​kakkoyun</code></a> <a
href="https://github.com/ArthurSens"><code>@​ArthurSens</code></a> <a
href="https://github.com/vesari"><code>@​vesari</code></a> <a
href="https://github.com/logicalhan"><code>@​logicalhan</code></a> <a
href="https://github.com/krajorama"><code>@​krajorama</code></a> <a
href="https://github.com/bwplotka"><code>@​bwplotka</code></a> who
helped in this patch release! 🤗</p>
<h3>Changelog</h3>
<p>[BUGFIX] testutil: Reverted <a
href="https://redirect.github.com/prometheus/client_golang/issues/1424">#1424</a>;
functions using compareMetricFamilies are (again) only failing if
filtered metricNames are in the expected input. <a
href="https://redirect.github.com/prometheus/client_golang/issues/1645">#1645</a></p>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/prometheus/client_golang/blob/main/CHANGELOG.md">github.com/prometheus/client_golang's
changelog</a>.</em></p>
<blockquote>
<h2>1.20.5 / 2024-10-15</h2>
<ul>
<li>[BUGFIX] testutil: Reverted <a
href="https://redirect.github.com/prometheus/client_golang/issues/1424">#1424</a>;
functions using compareMetricFamilies are (again) only failing if
filtered metricNames are in the expected input.</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/prometheus/client_golang/commit/48e12a185519fd76b4e514b597483781d9ba4093"><code>48e12a1</code></a>
Merge pull request <a
href="https://redirect.github.com/prometheus/client_golang/issues/1645">#1645</a>
from prometheus/cut-1204-pr1424</li>
<li><a
href="https://github.com/prometheus/client_golang/commit/504ad9bf5c6419449d2cacf8cf8855bfdcfcfc18"><code>504ad9b</code></a>
Cut 1.20.5; update comments.</li>
<li><a
href="https://github.com/prometheus/client_golang/commit/584a7ce3d935e4fdca7b893f5f741d59f3289140"><code>584a7ce</code></a>
Revert &quot;testutil compareMetricFamilies: make less error-prone (<a
href="https://redirect.github.com/prometheus/client_golang/issues/1424">#1424</a>)&quot;</li>
<li>See full diff in <a
href="https://github.com/prometheus/client_golang/compare/v1.20.4...v1.20.5">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>