Bump github.com/grafana/grafana-plugin-sdk-go from 0.259.4 to 0.260.0 in /plugin in the all group (#514)
Bumps the all group in /plugin with 1 update:
[github.com/grafana/grafana-plugin-sdk-go](https://github.com/grafana/grafana-plugin-sdk-go).

Updates `github.com/grafana/grafana-plugin-sdk-go` from 0.259.4 to
0.260.0
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/grafana/grafana-plugin-sdk-go/releases">github.com/grafana/grafana-plugin-sdk-go's
releases</a>.</em></p>
<blockquote>
<h2>v0.260.0</h2>
<h2>What's Changed</h2>
<ul>
<li>build(deps): bump golang.org/x/oauth2 from 0.23.0 to 0.24.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1153">grafana/grafana-plugin-sdk-go#1153</a></li>
<li>build(deps): bump golang.org/x/net from 0.30.0 to 0.31.0 by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a> in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1154">grafana/grafana-plugin-sdk-go#1154</a></li>
<li>build(deps): bump github.com/stretchr/testify from 1.9.0 to 1.10.0
by <a href="https://github.com/dependabot"><code>@​dependabot</code></a>
in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1156">grafana/grafana-plugin-sdk-go#1156</a></li>
<li>Deprecate <code>experimental/errorsource</code> and remove
<code>experimental/errorsource/httpclient</code> by <a
href="https://github.com/ivanahuckova"><code>@​ivanahuckova</code></a>
in <a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/pull/1150">grafana/grafana-plugin-sdk-go#1150</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.259.4...v0.260.0">https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.259.4...v0.260.0</a></p>
<h2>Compatibility</h2>
<p>Below incompatible changes in
<code>github.com/grafana/grafana-plugin-sdk-go/experimental/errorsource</code>
should be compatible since we've introduced type aliases and seems like
gorelease doesn't take that into consideration. Main change is changing
<code>Error</code> to a type alias for
<code>status.ErrorWithSource</code>. Additionally, we have removed the
experimental package
<code>github.com/grafana/grafana-plugin-sdk-go/experimental/errorsource/httpclient</code>,
as the error source middleware is now included in the HTTP client by
default. Consequently, this experimental package is no longer
needed.</p>
<pre><code>grafana-plugin-sdk-go % gorelease -base v0.259.4 -version
v0.260.0
# github.com/grafana/grafana-plugin-sdk-go/backend
## compatible changes
ErrorResponseWithErrorSource: added
ErrorWithSource: added
NewErrorWithSource: added
PluginError: added
<h1>github.com/grafana/grafana-plugin-sdk-go/backend/httpclient</h1>
<h2>compatible changes</h2>
<p>ErrorSourceRoundTripper: added</p>

<h1>github.com/grafana/grafana-plugin-sdk-go/experimental/errorsource</h1>
<h2>incompatible changes</h2>
<p>Error: changed from Error to
github.com/grafana/grafana-plugin-sdk-go/experimental/status.ErrorWithSource<br
/>
New: changed from func(error,
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source,
github.com/grafana/grafana-plugin-sdk-go/backend.Status) Error to
func(error,
github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source,
github.com/grafana/grafana-plugin-sdk-go/backend.Status)
github.com/grafana/grafana-plugin-sdk-go/experimental/status.ErrorWithSource<br
/>
SourceError: changed from
func(github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source,
error, bool) Error to
func(github.com/grafana/grafana-plugin-sdk-go/experimental/status.Source,
error, bool)
github.com/grafana/grafana-plugin-sdk-go/experimental/status.ErrorWithSource</p>

<h1>github.com/grafana/grafana-plugin-sdk-go/experimental/errorsource/httpclient</h1>
<h2>incompatible changes</h2>
<p>package removed</p>
<h1>github.com/grafana/grafana-plugin-sdk-go/experimental/status</h1>
<h2>compatible changes</h2>
<p>ErrorWithSource: added<br />
NewErrorWithSource: added<br />
PluginError: added</p>
<h1>summary</h1>
<p>v0.260.0 is a valid semantic version for this release.<br />
</code></pre></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/96b34c30fedac593b1c54dc7e2f315caed067b2e"><code>96b34c3</code></a>
Deprecate <code>experimental/errorsource</code> and remove
`experimental/errorsource/htt...</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/66c983fae2ae10f731b84c5368a7ca7227bf4f31"><code>66c983f</code></a>
build(deps): bump github.com/stretchr/testify from 1.9.0 to 1.10.0 (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1156">#1156</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/10f03df73d5c3b80da61bddd51deb459be0b7955"><code>10f03df</code></a>
build(deps): bump golang.org/x/net from 0.30.0 to 0.31.0 (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1154">#1154</a>)</li>
<li><a
href="https://github.com/grafana/grafana-plugin-sdk-go/commit/a9d4b7b564ddca5b258a7f91871b89d747290be0"><code>a9d4b7b</code></a>
build(deps): bump golang.org/x/oauth2 from 0.23.0 to 0.24.0 (<a
href="https://redirect.github.com/grafana/grafana-plugin-sdk-go/issues/1153">#1153</a>)</li>
<li>See full diff in <a
href="https://github.com/grafana/grafana-plugin-sdk-go/compare/v0.259.4...v0.260.0">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=github.com/grafana/grafana-plugin-sdk-go&package-manager=go_modules&previous-version=0.259.4&new-version=0.260.0)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>