Migrate golangci-lint to v2 (#1025)
# What Changed?
https://github.com/golangci/golangci-lint recently upgraded to v2, we
should upgrade as well!

1. Ran the migration command `golangci-lint migrate`
2. Updated the `make lint` target to use the latest version of
golangci-lint
3. Addressed the lint issues introduced by the migration (see below)

### Open questions
1. Is there a minimum supported GoLang version? Some newer syntax like
[ranging over integers](https://go.dev/doc/go1.22#language) (go 1.22+)
and [`maps.Copy` using generics](https://go.dev/doc/go1.21#maps) (go
1.21+) were flagged by the LSP while I was working in the repo. I
updated some, but they aren't backwards compatible with older go
versions so I can revert them if needed.
2. There is a delta between the [linters from
v1](https://golangci.github.io/legacy-v1-doc/usage/linters/) and the
[linters in v2](https://golangci-lint.run/docs/linters/). Feel free to
let me know if any of these need to be adjusted in the new config.
3. There are a bunch of new lints showing up when I run `make lint`
locally (see below) which I addressed, but might be better to add to
ignorelist.

### Requested Reviewers (can't assign right now)
@IfSentient
@stephaniehingtgen

### New Lints introduced after the migration
```bash
% make lint
target/golangci-lint-2.5.0 run  ./... ./plugin/... ./examples/apiserver/... ./logging/...
examples/resource/store/store.go:200:31: Error return value of `simpleStore.UpdateSubresource` is not checked (errcheck)
	simpleStore.UpdateSubresource(context.TODO(), resource.Identifier{
	                             ^
codegen/jennies/resourceobject.go:138:68: string `metadata` has 5 occurrences, make it a constant (goconst)
		if it.Selector().String() == "spec" || it.Selector().String() == "metadata" {
		                                                                 ^
examples/operator/simple/watcher/main.go:132:1: File is not properly formatted (gofmt)
			Kind:    kind,
^
examples/apiserver/apis/example/v0alpha1/testkind_client_gen.go:6:1: File is not properly formatted (goimports)
	"github.com/grafana/grafana-app-sdk/resource"
^
examples/resource/store/store.go:12:1: File is not properly formatted (goimports)
	"github.com/grafana/grafana-app-sdk/k8s"
^
examples/resource/store/store.go:133:15: ineffectual assignment to err (ineffassign)
	obj2Updated, err := store.UpdateSubresource(context.TODO(), obj2Kind.Kind(), resource.Identifier{
	             ^
examples/resource/store/store.go:181:15: ineffectual assignment to err (ineffassign)
	simpleStore, err := resource.NewSimpleStore[Obj2Spec](obj2Kind, generator)
	             ^
examples/resource/store/store.go:206:2: ineffectual assignment to err (ineffassign)
	err = simpleStore.Delete(context.TODO(), resource.Identifier{
	^
examples/resource/store/store.go:82:132: `cancelled` is a misspelling of `canceled` (misspell)
			WaitForAvailability: true, // Wait for the schema to be available in the system (creates can be async), or until the context is cancelled
			                                                                                                                                ^
cmd/grafana-app-sdk/manifest.go:27:14: unnecessary-format: unnecessary use of formatting function "fmt.Errorf", you can replace it with "errors.New" (revive)
		return "", fmt.Errorf("no data")
		           ^
cmd/grafana-app-sdk/manifest.go:65:15: unnecessary-format: unnecessary use of formatting function "fmt.Errorf", you can replace it with "errors.New" (revive)
		return nil, fmt.Errorf("no data")
		            ^
cmd/grafana-app-sdk/project_local_datasources.go:11:18: unsecure-url-scheme: prefer secure protocol https over http in "http://cortex.default.svc.cluster.local:9009/api/prom" (revive)
			URL:          "http://cortex.default.svc.cluster.local:9009/api/prom",
			              ^
cmd/grafana-app-sdk/project_local_datasources.go:19:12: unsecure-url-scheme: prefer secure protocol https over http in "http://tempo.default.svc.cluster.local:3100" (revive)
			URL:    "http://tempo.default.svc.cluster.local:3100",
			        ^
cmd/grafana-app-sdk/project_local_datasources.go:26:18: unsecure-url-scheme: prefer secure protocol https over http in "http://loki.default.svc.cluster.local:3100" (revive)
			URL:          "http://loki.default.svc.cluster.local:3100",
			              ^
cmd/grafana-app-sdk/util.go:136:13: unnecessary-format: unnecessary use of formatting function "fmt.Errorf", you can replace it with "errors.New" (revive)
	return "", fmt.Errorf("unable to locate module in go.mod file")
	           ^
codegen/jennies/resourceobject.go:167:47: identical-ifelseif-branches: "if...else if" chain with identical branches (lines 171 and 174) (revive)
	if strings.Contains(typeString, "time.Time") {
		return templates.GoTypeTime
	} else if strings.Contains(typeString, "int") {
examples/apiserver/server.go:238:2: enforce-switch-style: switch must have a default case clause (revive)
	switch srcGVK.Version {
	case v0alpha1.APIVersion:
		srcKind := v0alpha1.TestKindKind()
		uncastSrcObj, err := srcKind.Read(bytes.NewReader(obj.Raw), resource.KindEncodingJSON)
		if err != nil {
			return nil, fmt.Errorf("unable to parse JSON bytes into %s: %w", srcGVK.String(), err)
		}
		srcObj, ok := uncastSrcObj.(*v0alpha1.TestKind)
		if !ok {
			return nil, errors.New("read object was not of type *v0alpha1.Example")
		}
		switch dstGVK.Version {
		case v1alpha1.APIVersion:
			dstObj := &v1alpha1.TestKind{}
			// Set Type metadata
			dstObj.SetGroupVersionKind(dstGVK)
			// Copy Object metadata
			srcObj.ObjectMeta.DeepCopyInto(&dstObj.ObjectMeta)
			// Copy spec and status
			dstObj.Spec.TestField = strconv.Itoa(int(srcObj.Spec.TestField))
			dstObj.Status.AdditionalFields = srcObj.Status.AdditionalFields
			if srcObj.Status.OperatorStates != nil {
				dstObj.Status.OperatorStates = make(map[string]v1alpha1.TestKindstatusOperatorState)
				for k, v := range srcObj.Status.OperatorStates {
					dstObj.Status.OperatorStates[k] = v1alpha1.TestKindstatusOperatorState{
						LastEvaluation:   v.LastEvaluation,
						State:            v1alpha1.TestKindStatusOperatorStateState(v.State),
						DescriptiveState: v.DescriptiveState,
						Details:          v.Details,
					}
				}
			}
			dstKind := v1alpha1.TestKindKind()
			buf := &bytes.Buffer{}
			err := dstKind.Write(dstObj, buf, resource.KindEncodingJSON)
			return buf.Bytes(), err
		default:
			return nil, fmt.Errorf("unknown target version %s", dstGVK.Version)
		}
	case v1alpha1.APIVersion:
		srcKind := v1alpha1.TestKindKind()
		uncastSrcObj, err := srcKind.Read(bytes.NewReader(obj.Raw), resource.KindEncodingJSON)
		if err != nil {
			return nil, fmt.Errorf("unable to parse JSON bytes into %s: %w", srcGVK.String(), err)
		}
		srcObj, ok := uncastSrcObj.(*v1alpha1.TestKind)
		if !ok {
			return nil, errors.New("read object was not of type *v1alpha1.Example")
		}
		switch dstGVK.Version {
		case v0alpha1.APIVersion:
			dstObj := &v0alpha1.TestKind{}
			// Set Type metadata
			dstObj.SetGroupVersionKind(dstGVK)
			// Copy Object metadata
			srcObj.ObjectMeta.DeepCopyInto(&dstObj.ObjectMeta)
			// Copy spec and status
			castInt, _ := strconv.Atoi(srcObj.Spec.TestField) // Lossy backwards conversion
			dstObj.Spec.TestField = int64(castInt)
			dstObj.Status.AdditionalFields = srcObj.Status.AdditionalFields
			if srcObj.Status.OperatorStates != nil {
				dstObj.Status.OperatorStates = make(map[string]v0alpha1.TestKindstatusOperatorState)
				for k, v := range srcObj.Status.OperatorStates {
					dstObj.Status.OperatorStates[k] = v0alpha1.TestKindstatusOperatorState{
						LastEvaluation:   v.LastEvaluation,
						State:            v0alpha1.TestKindStatusOperatorStateState(v.State),
						DescriptiveState: v.DescriptiveState,
						Details:          v.Details,
					}
				}
			}
			dstKind := v0alpha1.TestKindKind()
			buf := &bytes.Buffer{}
			err := dstKind.Write(dstObj, buf, resource.KindEncodingJSON)
			return buf.Bytes(), err
		default:
			return nil, fmt.Errorf("unknown target version %s", dstGVK.Version)
		}
	}
examples/operator/simple/reconciler/main.go:46:3: unhandled-error: Unhandled error in call to function fmt.Println (revive)
		fmt.Println("--kubecfg must be set to the path of your kubernetes config file")
		^
examples/operator/simple/reconciler/main.go:109:23: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
		ReconcileFunc: func(ctx context.Context, request operator.ReconcileRequest) (operator.ReconcileResult, error) {
		                    ^
examples/operator/simple/watcher/main.go:109:17: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
		AddFunc: func(ctx context.Context, object resource.Object) error {
		              ^
examples/operator/simple/watcher/main.go:113:46: redefines-builtin-id: redefinition of the built-in function new (revive)
		UpdateFunc: func(ctx context.Context, old, new resource.Object) error {
		                                           ^
examples/operator/simple/watcher/main.go:117:20: unused-parameter: parameter 'ctx' seems to be unused, consider removing or renaming it as _ (revive)
		DeleteFunc: func(ctx context.Context, object resource.Object) error {
		                 ^
examples/resource/store/store.go:57:3: unhandled-error: Unhandled error in call to function fmt.Println (revive)
		fmt.Println("--kubecfg must be set to the path of your kubernetes config file")
		^
examples/resource/store/store.go:79:3: defer: prefer not to defer inside loops (revive)
		defer cancel()
		^
examples/resource/store/store.go:130:2: unhandled-error: Unhandled error in call to function fmt.Println (revive)
	fmt.Println("Hi")
	^
examples/resource/store/store.go:217:1: comment-spacings: no space between comment delimiter and comment text (revive)
/**
 *
 * OBJECT STRUCTS
 * Typically, these are generated. Here, to keep this example self-contained, we define them
 * TODO: Maybe generate these and commit generated code?
 * TODO: Will need codegen to work with subresources
 *
 */
k8s/negotiator.go:126:3: enforce-switch-style: switch must have a default case clause (revive)
		switch encoding {
		case resource.KindEncodingJSON:
			serializer.Decoder = json.Unmarshal
			info.Serializer = serializer
			info.StreamSerializer = &runtime.StreamSerializerInfo{
				Serializer: serializer,
				Framer:     jsonserializer.Framer,
			}
		case resource.KindEncodingYAML:
			// TODO: YAML framer
			//	framer = yamlserializer.Framer <- doesn't exist
		}
k8s/translation.go:142:2: enforce-switch-style: switch must have a default case clause (revive)
	switch req.Operation {
	case admission.Create:
		action = resource.AdmissionActionCreate
	case admission.Update:
		action = resource.AdmissionActionUpdate
	case admission.Delete:
		action = resource.AdmissionActionDelete
	case admission.Connect:
		action = resource.AdmissionActionConnect
	}
resource/object.go:241:3: identical-switch-branches: "switch" with identical branches (lines 253 and 258) (revive)
		switch src.Type().Elem().Kind() {
		case reflect.Struct:
			if src.Elem().Type() == reflectTypeTime {
				dst.Set(src)
				return nil
			}
			dstPtr := reflect.New(typ).Interface()
			err := CopyObjectInto(dstPtr, src.Interface())
			if err != nil {
				return err
			}
			dst.Set(reflect.ValueOf(dstPtr))
		case reflect.Slice:
			if dst.IsNil() {
				dst.Set(reflect.New(typ))
			}
			return copyReflectValueInto(dst.Elem(), src.Elem())
		case reflect.Map:
			if dst.IsNil() {
				dst.Set(reflect.New(typ))
			}
			return copyReflectValueInto(dst.Elem(), src.Elem())
		default:
			ptrCopy := reflect.New(src.Type().Elem()) // new pointer of the same _value type_ as src
			ptrCopy.Elem().Set(src.Elem())            // copy the value src is pointing to
			dst.Set(ptrCopy)
		}
codegen/cuekind/parser.go:137:10: ST1023: should omit type cue.Value from declaration; it will be inferred from the right-hand side (staticcheck)
	var val cue.Value = root
	        ^
codegen/jennies/gotypes.go:130:62: QF1001: could apply De Morgan's law (staticcheck)
			AddKubernetesOpenAPIGenComment: g.AddKubernetesCodegen && !(len(fieldName) == 1 && fieldName[0] == "metadata"),
			                                                          ^
examples/resource/store/store.go:121:7: QF1008: could remove embedded field "ObjectMeta" from selector (staticcheck)
	obj2.ObjectMeta.Namespace = "default"
	     ^
examples/resource/store/store.go:122:7: QF1008: could remove embedded field "ObjectMeta" from selector (staticcheck)
	obj2.ObjectMeta.Name = "example-1" // We can use the same name, because it's a different resource kind
	     ^
k8s/webhooks.go:221:3: QF1012: Use fmt.Fprintf(...) instead of Write([]byte(fmt.Sprintf(...))) (staticcheck)
		writer.Write([]byte(fmt.Sprintf(errStringNoAdmissionControllerDefined, "validating", admRev.Request.RequestKind.Group, admRev.Request.RequestKind.Kind)))
		^
k8s/webhooks.go:298:3: QF1012: Use fmt.Fprintf(...) instead of Write([]byte(fmt.Sprintf(...))) (staticcheck)
		writer.Write([]byte(fmt.Sprintf(errStringNoAdmissionControllerDefined, "mutating", admRev.Request.RequestKind.Group, admRev.Request.RequestKind.Kind)))
		^
resource/kind.go:158:4: QF1008: could remove embedded field "ListMeta" from selector (staticcheck)
	t.ListMeta.DeepCopyInto(&cpy.ListMeta)
	  ^
resource/typedobject.go:34:16: QF1008: could remove embedded field "ObjectMeta" from selector (staticcheck)
		Name:      t.ObjectMeta.Name,
		             ^
resource/typedobject.go:587:46: QF1008: could remove embedded field "TypeMeta" from selector (staticcheck)
	if err = json.Unmarshal(m["apiVersion"], &t.TypeMeta.APIVersion); err != nil {
	                                            ^
resource/typedobject.go:590:40: QF1008: could remove embedded field "TypeMeta" from selector (staticcheck)
	if err = json.Unmarshal(m["kind"], &t.TypeMeta.Kind); err != nil {
	                                      ^
resource/untypedobject.go:96:46: QF1008: could remove embedded field "TypeMeta" from selector (staticcheck)
	if err = json.Unmarshal(m["apiVersion"], &u.TypeMeta.APIVersion); err != nil {
	                                            ^
resource/untypedobject.go:266:4: QF1008: could remove embedded field "ListMeta" from selector (staticcheck)
	u.ListMeta.DeepCopyInto(&cpy.ListMeta)
	  ^
simple/operator.go:86:15: QF1008: could remove embedded field "MetricsServerConfig" from selector (staticcheck)
		cfg.Metrics.MetricsServerConfig.Port = 9090
		            ^
simple/operator.go:89:17: QF1008: could remove embedded field "MetricsServerConfig" from selector (staticcheck)
	if cfg.Metrics.MetricsServerConfig.HealthCheckInterval <= 0 {
	               ^
43 issues:
* errcheck: 1
* goconst: 1
* gofmt: 1
* goimports: 2
* ineffassign: 3
* misspell: 1
* revive: 20
* staticcheck: 14
```