codegen: remove CLI flags and provide error on their usage (#1278)
## What Changed? Why?

Removes the CLI flags that have been replaced with a config cue block.
If someone attempts to use the flags, they will get an error like below:
```bash
grafana-app-sdk generate --grouping=kind --gogenpath=pkg/gen1 --tsgenpath=ts/gen1 --gomodgenpath="pkg/generated" --defencoding=json --manifest=customManifest --crdmanifest
```
```
Error: CLI flags have been replaced by CUE defined config values:
 --grouping -> kinds.grouping
 --gogenpath -> codegen.goGenPath
 --tsgenpath -> codegen.tsGenPath
 --gomodgenpath -> codegen.goModGenPath
 --defencoding -> definitions.encoding (if set to 'none' -> definitions.genManifest=false, definitions.genCRDs=false)
 --manifest -> manifestSelectors
 --crdmanifest -> definitions.manifestVersion
Follow this migration guide https://github.com/grafana/grafana-app-sdk/blob/main/docs/migrations/v0.52.md to migrate your usage of CLI flags to the new CUE config values
```

### How was it tested?
Unit, integration tests pass, no change to existing generated code.