Revert CUELang version to match cog's (#1143)
## What Changed? Why?

Revert CUELang version to match cog's, as the mismatch was causing
errors with list defaults in codegen.

Retract the patch version which updated CUE, so that folks won't be able
to pull this version by mistake.

### How was it tested?

Locally, against `github.com/grafana/grafana/apps/dashboard`

Error with `v0.48.6` prior to this change:
```
Error: 1 error occurred:
        * GoTypes: [v2alpha1] /github.com/grafana/grafana/sdkkinds/dashboard/v2alpha1/dashboard_spec.cue:547:2: open list must have a type for input "Dashboard"
```

The codegen completes successfully when using the reverted version
installed locally.